version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
    groups:
      patches-and-minors:
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
    groups:
      patches-and-minors:
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
    groups:
      patches-and-minors:
        update-types:
          - patch
          - minor

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
